name: Run Unit Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  Unit-Test:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Unit Test
        run: |
          call ${{secrets.ANACONDA3_PATH}}/Scripts/activate.bat gc_poc
          pytest -v
        shell: cmd