name: Run Unit Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  Unit-Test:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Unit Test
        run: |
          call ${{secrets.ANACONDA3_PATH}}/Scripts/activate.bat gc_poc
          python dm_unit_test.py 
        shell: cmd